<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Clients extends CI_Controller
{

   function __construct()
{
    parent :: __construct();
   
        $this->load->library('form_validation');
        $this->load->helper('form');
        $this->load->helper('url');
        $this->load->database();
         $this->load->model('Clients_model');
    }

      
    public function simpan() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->session->set_flashdata('messageAlert', $this->messageAlert('error', 'Data tidak tersimpan, coba beberapa saat lagi'));
            redirect('welcome');
        } else {
            $data = array(
		'name' => $this->input->post('name',TRUE),
		
		'email' => $this->input->post('email',TRUE),
	
		'message' => $this->input->post('message',TRUE),
	    );

            $this->Clients_model->insert($data);
            $this->session->set_flashdata('messageAlert', $this->messageAlert('success', 'Terimakasih telah menghubungi kami'));
              redirect('welcome');
        }
    }
    
   public function _rules() 
    {
    $this->form_validation->set_rules('name', 'name', 'trim|required');
    $this->form_validation->set_rules('email', 'email', 'trim|required');
    $this->form_validation->set_rules('message', 'message', 'trim');
    $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }
   
    public function messageAlert($type, $title) {
      $messageAlert = "
      const Toast = Swal.mixin({
          toast: true,
          position: 'top-end',
          showConfirmButton: false,
          timer: 5000
      });

      Toast.fire({
          type: '".$type."',
          title: '".$title."'
      });
      ";
      return $messageAlert;
  }

}

/* End of file Pengguna.php */
/* Location: ./application/controllers/Pengguna.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-17 21:32:57 */
/* http://harviacode.com */